"""UI-Related Constants and Strings"""

PLACEHOLDER_TXT = "Write here..."
HOME = "Home"
ENTER_BUTTON = "Invio"
REVISE = "Ripassa"
CREATE_DECK = "Crea mazzo"
EDIT_DECK = "Modifica mazzo"
IMPORT_DECK = "Importa mazzo"
EXIT = "Esci"

MENU_TITLE = "Menu"
SELECT_MENU_ITEM = "Seleziona una voce"
UNKNOWN_CONTENT_TYPE = "Tipo sconosciuto: {type_name}"
DECK_SELECTOR_TITLE = "Seleziona un mazzo"
DECK_SELECTOR_EMPTY = "Nessun mazzo disponibile nei deck locali."
DECK_SELECTOR_ITEM = "{deck_name} ({card_count} domande)"

DECK_CREATOR_TITLE = "Crea un nuovo mazzo"
DECK_CREATOR_DECK_PLACEHOLDER = "Nome mazzo"
DECK_CREATOR_QUESTION_PLACEHOLDER = "Domanda"
DECK_CREATOR_ANSWER_PLACEHOLDER = "Risposta"
DECK_CREATOR_TIP_PLACEHOLDER = "Suggerimento (opzionale)"
DECK_CREATOR_TAGS_PLACEHOLDER = "Tag separati da virgola"
DECK_CREATOR_BACK_BUTTON = "Indietro"
DECK_CREATOR_CREATE_DECK_BUTTON = "Crea mazzo"
DECK_CREATOR_CREATE_CARD_BUTTON = "Crea domanda"
DECK_CREATOR_SAVE_BUTTON = "Salva"
DECK_CREATOR_CARD_CREATED = "Domanda aggiunta al mazzo {deck_name}. Totale domande: {card_count}"
DECK_CREATOR_SUCCESS = "Mazzo salvato: {deck_name}"
DECK_CREATOR_DECK_ERROR = "Inserisci il nome del mazzo prima di crearlo."
DECK_CREATOR_MISSING_DECK = "Crea prima un mazzo."
DECK_CREATOR_CARD_ERROR = "Compila almeno domanda e risposta."
DECK_CREATOR_EMPTY_DECK = "Aggiungi almeno una domanda prima di salvare."
DECK_CREATOR_UNSAVED_WARNING = "Hai modifiche non salvate. Salva il mazzo prima di uscire da questa schermata."

DECK_MANAGER_TITLE = "Gestisci i mazzi"
DECK_MANAGER_EMPTY = "Nessun mazzo disponibile da gestire."
DECK_MANAGER_SELECTED_LABEL = "Mazzo selezionato"
DECK_MANAGER_COUNT = "Domande nel mazzo: {card_count}"
DECK_MANAGER_RENAME_LABEL = "Nuovo nome mazzo"
DECK_MANAGER_RENAME_BUTTON = "Rinomina"
DECK_MANAGER_RENAME_ERROR = "Inserisci un nuovo nome mazzo."
DECK_MANAGER_RENAME_SUCCESS = "Mazzo rinominato: {deck_name}"
DECK_MANAGER_CREATE_BUTTON = "Nuovo mazzo"
DECK_MANAGER_OPEN_BUTTON = "Apri"

DECK_MANAGER_ACTIONS_TITLE = "Azioni sul mazzo"
DECK_MANAGER_ACTIONS_BACK_BUTTON = "Torna"
DECK_MANAGER_DUPLICATE_BUTTON = "Duplica"
DECK_MANAGER_EDIT_BUTTON = "Modifica"
DECK_MANAGER_DELETE_BUTTON = "Elimina"
DECK_MANAGER_DELETE_CONFIRM_TEXT = "Confermi l'eliminazione del mazzo corrente?"
DECK_MANAGER_DELETE_CONFIRM_BUTTON = "Conferma elimina"
DECK_MANAGER_DELETE_CANCEL_BUTTON = "Annulla"

DECK_EDITOR_TITLE = "Modifica il mazzo"
DECK_EDITOR_CREATE_TITLE = "Crea un mazzo"
DECK_EDITOR_EMPTY = "Nessun mazzo disponibile da modificare."
DECK_EDITOR_DECK_LABEL = "Mazzo"
DECK_EDITOR_CREATE_BUTTON = "Nuovo mazzo"
DECK_EDITOR_PREV_DECK_BUTTON = "Prec."
DECK_EDITOR_NEXT_DECK_BUTTON = "Succ."
DECK_EDITOR_NAME_PLACEHOLDER = "Nome mazzo"
DECK_EDITOR_PROGRESS = "Domanda {current}/{total}"
DECK_EDITOR_CARD_NUMBER_LABEL = "Numero domanda"
DECK_EDITOR_CARD_NUMBER_BUTTON = "Vai"
DECK_EDITOR_CARD_NUMBER_ERROR = "Numero domanda non valido."
DECK_EDITOR_LOAD_ERROR = "Impossibile caricare il mazzo selezionato."
DECK_EDITOR_CARD_ERROR = "Compila almeno domanda e risposta."
DECK_EDITOR_SAVE_SUCCESS = "Mazzo salvato: {deck_name}"
DECK_EDITOR_DELETE_SUCCESS = "Mazzo eliminato: {deck_name}"
DECK_EDITOR_DELETE_ERROR = "Nessun mazzo da eliminare."
DECK_EDITOR_NAME_ERROR = "Inserisci un nome mazzo."
DECK_EDITOR_UNSAVED_WARNING = "Hai modifiche non salvate. Salva il mazzo prima di uscire."
DECK_EDITOR_PREV_BUTTON = "<"
DECK_EDITOR_NEXT_BUTTON = ">"
DECK_EDITOR_NEW_BUTTON = "Nuova domanda"
DECK_EDITOR_REMOVE_BUTTON = "Rimuovi domanda"
DECK_EDITOR_BACK_BUTTON = "Indietro"
DECK_EDITOR_CANCEL_BUTTON = "Annulla modifiche"
DECK_EDITOR_SAVE_BUTTON = "Salva modifiche"
DECK_EDITOR_DELETE_BUTTON = "Elimina mazzo"

DECK_IMPORTER_TITLE = "Importa un mazzo"
DECK_IMPORTER_URL_PLACEHOLDER = "URL del file .json"
DECK_IMPORTER_NAME_PLACEHOLDER = "Nome mazzo (opzionale)"
DECK_IMPORTER_IMPORT_BUTTON = "Importa"
DECK_IMPORTER_READY_STATUS = "Inserisci un URL JSON valido per importare un mazzo."
DECK_IMPORTER_URL_ERROR = "Inserisci un URL del deck."
DECK_IMPORTER_INVALID_DECK = "Impossibile importare il deck dal link fornito."
DECK_IMPORTER_SUCCESS = "Mazzo importato: {deck_name}"
DECK_IMPORTER_NAME_ERROR = "Impossibile determinare il nome del mazzo. Inseriscilo manualmente."
DECK_IMPORTER_DEPENDENCY_ERROR = "Import remoto non disponibile: manca la dipendenza requests."

QUESTION_MENU_TITLE = "Allenamento domande"
QUESTION_MENU_INPUT_LABEL = "La tua risposta"
QUESTION_MENU_INPUT_PLACEHOLDER = "Scrivi qui la tua risposta..."
QUESTION_MENU_REVEAL_BUTTON = "Mostra risposta"
QUESTION_MENU_CORRECT_BUTTON = "Corretto"
QUESTION_MENU_WRONG_BUTTON = "Sbagliato"
QUESTION_MENU_NEXT_BUTTON = "Prossima"
QUESTION_MENU_PREVIOUS_BUTTON = "Indietro"
QUESTION_MENU_HOME_BUTTON = "Torna alla home"
QUESTION_MENU_FINISH_BUTTON = "Fine"
QUESTION_MENU_NO_QUESTIONS = "Nessuna domanda disponibile"
QUESTION_MENU_NO_QUESTIONS_HINT = "Aggiungi un deck o configura delle domande in ui_constants.py"
QUESTION_MENU_EMPTY_ANSWER = ""
QUESTION_MENU_EMPTY_TIP = ""
QUESTION_MENU_QUESTION_MISSING = "Domanda non disponibile"
QUESTION_MENU_ANSWER_MISSING = "Risposta non disponibile"
QUESTION_MENU_HINT_PREFIX = "Suggerimento"
QUESTION_MENU_QUESTION_PREFIX = "Q"
QUESTION_MENU_ANSWER_PREFIX = "A"
QUESTION_MENU_HIDDEN_ANSWER = ""
QUESTION_MENU_PROGRESS = "Domanda {current}/{total}"
QUESTION_MENU_STATS = "Corrette: {correct} | Sbagliate: {wrong}"

SHOW_RESULTS_TITLE = "Report finale"
SHOW_RESULTS_CORRECT = "Risposte corrette: {correct}"
SHOW_RESULTS_WRONG = "Risposte sbagliate: {wrong}"
SHOW_RESULTS_TOTAL = "Totale domande: {total}"
SHOW_RESULTS_ACCURACY = "Accuratezza: {accuracy:.0f}%"
SHOW_RESULTS_HOME_BUTTON = "Torna alla home"

MENU_PAGES = {
    HOME: {
        "type": "home"
    },
    REVISE: {
        "type": "deck_selector"
    },
    EDIT_DECK: {
        "type": "deck_manager"
    },
    IMPORT_DECK: {
        "type": "deck_importer"
    },
    EXIT: {
        "type": "exit"
    }
}
